drive_motors:
- {GPIO: 117, PWM: 0, position: front_right}  # Drive motor 0: P9_31 (pwm0/ehr0A), P9_25 (gpio117)
- {GPIO: 115, PWM: 1, position: front_left}   # Drive motor 1: P9_29 (pwm1/ehr0B), P9_27 (gpio115)
- {GPIO: 47, PWM: 5, position: back_left}     # Drive motor 2: P8_19 (pwm5/ehr2B), P8_15 (gpio47)
- {GPIO: 45, PWM: 6, position: back_right}    # Drive motor 3: P8_13 (pwm6/ehr2A), P8_11 (gpio45)
turret_servos:
- {PWM: 2, axis: servo_x}  # Turret servo - pan: P9_42 (pwm2/ecap0)
- {PWM: 7, axis: servo_y}  # Turret servo - tilt: P9_28 (pwm7/ecap2)
gun_motors:
- {PWM: 3}  # Gun motor 0: P9_14 (pwm3/ehr1A)
- {PWM: 4}  # Gun motor 1: P9_16 (pwm4/ehr1B)
gun_sol: {GPIO: 60}  # Gun solenoid/trigger: P9_12 (gpio60)
sol_extend_delay: 0.5
ir_select_gpios: [44, 26, 46, 65]  # GPIOs to select IR sensor units: [P8_12 (gpio44), P8_14 (gpio26), P8_16 (gpio46), P8_18 (gpio65)]
ir_input_adcs: {front: 0, back: 4, left: 1, right: 2}  # Input ADC pins to read selected IR sensor units: P9_39 (AIN0), P9_38 (AIN4), P9_40 (AIN1), P9_37 (AIN2)
logging: {log_file: logs/bot.log, file_handler_level: DEBUG, stream_handler_level: INFO}  # Logging options
strategy: planner/strategies/strategy0.yaml
targeting: gunner/targeting/targeting0.yaml
test_pwm_base_dir: simulator/pins/pwm/pwm
test_gpio_base_dir: simulator/pins/gpio/gpio
test_adc_base_dir: simulator/pins/adc
test_strat_base_dir: planner/tests/strategies/
fsm_tests: ./planner/tests/input/RobotNormalTest.txt
testing: false
server_port: tcp://*:60000
num_ir_arrays: 4
irs_per_array: 16

