drive_motors:
- {GPIO: 117, PWM: 0, position: front_right}  # Drive motor 0: P9_31 (pwm0/ehr0A), P9_25 (gpio117)
- {GPIO: 115, PWM: 1, position: front_left}   # Drive motor 1: P9_29 (pwm1/ehr0B), P9_27 (gpio115)
- {GPIO: 47, PWM: 5, position: back_left}     # Drive motor 2: P8_19 (pwm5/ehr2B), P8_15 (gpio47)
- {GPIO: 45, PWM: 6, position: back_right}    # Drive motor 3: P8_13 (pwm6/ehr2A), P8_11 (gpio45)
turret_servos:
- {PWM: 2, axis: yaw}  # Turret servo - pan: P9_42 (pwm2/ecap0)
- {PWM: 7, axis: pitch}  # Turret servo - tilt: P9_28 (pwm7/ecap2)
gun: {
    max_trigger_duration: 0.25,  # Maximum duration a trigger pin can be high
    laser_gpio: 8,  # Gun laser: P8_35 (gpio8)
    motor_gpios: {
        left: 78,  # Gun motor - left: P8_37 (gpio78)
        right: 76  # Gun motor - right: P8_39 (gpio76)
    },
    trigger_gpios: {
        retract: 74,  # Gun trigger - retract: P8_41 (gpio74)
        advance: 72   # Gun trigger - advance: P8_43 (gpio72)
    }
}
ultrasonics:
- {GPIO: -1, position: front}
- {GPIO: -1, position: left}
- {GPIO: -1, position: back}
- {GPIO: -1, position: right}
ir_select_gpios: [44, 26, 46, 65]  # GPIOs to select IR sensor units: [P8_12 (gpio44), P8_14 (gpio26), P8_16 (gpio46), P8_18 (gpio65)]
ir_input_adcs: {front: 0, back: 4, left: 1, right: 2}  # Input ADC pins to read selected IR sensor units: P9_39 (AIN0), P9_38 (AIN4), P9_40 (AIN1), P9_37 (AIN2)
logging: {log_file: logs/bot.log, file_handler_level: DEBUG, stream_handler_level: INFO}  # Logging options
strategy: planner/strategies/strategy0.yaml
targeting: gunner/targeting/targeting0.yaml
test_pwm_base_dir: simulator/pins/pwm/pwm
test_gpio_base_dir: simulator/pins/gpio/gpio
test_adc_base_dir: simulator/pins/adc
fsm_tests: ./planner/tests/input/RobotNormalTest.txt
testing: false
server_protocol: tcp
server_bind_host: "*"  # Special hostname servers bind to, for listening on all interfaces
server_host: 127.0.0.1  # Default hostname clients connect to
server_port: 60000  # (Primary) ControlServer port
pub_server_pub_port: 60001  # PubServer published bot data on this port
pub_server_topic_port: 60002  # PubServer is told topics to set on this port
irs_per_array: 16
