drive_motors:
- {GPIO: 0, PWM: 0, position: front_right}
- {GPIO: 1, PWM: 1, position: front_left}
- {GPIO: 2, PWM: 2, position: back_left}
- {GPIO: 3, PWM: 3, position: back_right}
gun_motors:
- {GPIO: 4, PWM: 4}
- {GPIO: 5, PWM: 5}
gun_sol: {GPIO: 6}
log_file: logs/bot.log
sol_extend_delay: 0.5
strategy: planner/strategies/strategy0.yaml
targeting: gunner/targeting/targeting0.yaml
test_gpio_base_dir: simulator/pins/gpio/gpio
test_pwm_base_dir: simulator/pins/pwm/pwm
test_strat_base_dir: planner/tests/strategies/
testing: false
turret_servos:
- {PWM: 6, axis: servo_x}
- {PWM: 7, axis: servo_y}
